### ISSUE TITLE
Página de criação de item de plano deveria informar o tipo de item

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/participe-web#10]
Na tela de criação de um item do plano, deveria ter a informação do tipo de item que está sendo criado.
No caso do print abaixo por exemplo, deveria ter a informação de que está sendo criado um "Desafio".

![image](https://user-images.githubusercontent.com/41954965/73572829-94a2ef80-4450-11ea-93aa-3b2fb104437a.png)

**Comment by nataliafvilalva** [comment]
Foi criado o ticket PAR-56 no Jira para melhoria.

**Comment by vdcordeiro** [comment]
A melhoria foi implementa para o Plano, no entanto devemos adotar a técnica como padrão e aplicar às demais telas de edição e criação.

**Comment by nataliafvilalva** [comment]
Melhoria feita nessa Sprint de correção. Publicada para teste.

**Comment by vdcordeiro** [comment]
O comportamento deve ser aplicado a todo o produto: Domínio, Estrutura, Plano e Consulta

**Comment by vdcordeiro** [comment]
Também na Moderação, se aplicável.
