### ISSUE TITLE
Falhas na responsividade 

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/participe-web#11]
A interface apresenta falhas de exibição em alguns tamanhos intermediários.

![image](https://user-images.githubusercontent.com/41954965/73573827-0ed47380-4453-11ea-989e-b2803ea706d9.png)

![image](https://user-images.githubusercontent.com/41954965/73573916-3e837b80-4453-11ea-89eb-3ec49cb6e498.png)

![image](https://user-images.githubusercontent.com/41954965/73574036-6ecb1a00-4453-11ea-8c67-89049f439e31.png)

**Comment by nataliafvilalva** [comment]
Foi criado o ticket PAR-50 para correção.

**Comment by nataliafvilalva** [comment]
Publicado para teste.
