### ISSUE TITLE
Moderação - Pesquisa

### ISSUE THREAD

**Issue by msantosmarcos** [sep-es-br/participe-web#118]
Na moderação a função de pesquisa esta com comportamento errôneo. Ao executar a pesquisa passando uma microrregião ou área estratégica que não possui propostas esta exibindo registros. conforme vídeo abaixo:

https://www.loom.com/share/71a4ee8f22b14df6a771d450f1f33737

**Comment by msantosmarcos** [comment]
O botão ocultar esta com link estendido demais. Favor reduzir

**Comment by msantosmarcos** [comment]
Por default colocar o Valor "Todos" nos itens de filtro.

**Comment by vdcordeiro** [comment]
Fixed cypher in api and hide button click space in the frontend

**Comment by msantosmarcos** [comment]
demanda executada com sucesso.
