### ISSUE TITLE
Relacionamentos incorretos no modelo

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/participe-web#12]
Alguns relacionamentos não fazem sentido no modelo registrado no banco:

![image](https://user-images.githubusercontent.com/41954965/73575390-d6cf2f80-4456-11ea-96d0-2f461e376a40.png)

De acordo com o grafo acima, 
- "Educação **_pertence_** ao arquivo brasao_rec.png". Há um erro de direção;
- "Educação **_pertence_** a Área Estratégica". O nome o relacionamento não é o mais adequado;
Além disso, o termo BELONGS_TO é utilizado para relacionamentos de natureza diferente, o que gera confusão ao modelo.

**Comment by nataliafvilalva** [comment]
Foi criado o ticket PAR-53 no Jira para correção. Aguardando o termo a ser utilizado no lugar de"BELONGS_TO".

**Comment by nataliafvilalva** [comment]
Publicado para teste.
