### ISSUE TITLE
Consulta - nome do servidor

### ISSUE THREAD

**Issue by msantosmarcos** [sep-es-br/participe-web#122]
Favor adicionar no label do nome do servidor um exemplo conforme imagem abaixo:

![image](https://user-images.githubusercontent.com/41967259/131540520-a1f91430-08f7-4e45-97bf-6c7558cf9cb6.png)

**Comment by vdcordeiro** [comment]
Adicionado ao input o placeholder **https://my.domain.com/**

**Comment by msantosmarcos** [comment]
demanda executada.
