### ISSUE TITLE
Editar Reunião

### ISSUE THREAD

**Issue by msantosmarcos** [sep-es-br/participe-web#124]
O sistema tem que deixar alterar o tipo de reunião, conforme imagem abaixo:

https://www.loom.com/share/d8b96c65ecf047799555f1ff4244f6b3

**Comment by MateusFirmino** [comment]
Não é um bug , documentação. https://totemti.atlassian.net/wiki/spaces/PARTICIPE/pages/1545076740/Manter+Reuni+o+2.0

**Comment by msantosmarcos** [comment]
ok, modificamos o status para melhoria.

**Comment by msantosmarcos** [comment]
não será feito
