### ISSUE TITLE
Administrador não edita/registra presença em todas as reuniões

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/participe-web#127]
Um administrador, diferente do recepcionista, deveria ser capaz acessar as telas para preenchimento e edição da lista de presença de todas as reuniões. Isso não ocorre. Somente as reuniões em curso no momento ficam visíveis para o administrador selecionar, registrar presença e editar lista.

Veja no vídeo abaixo que sem uma reunião em curso no momento o administrador não consegue acessar nenhuma lista de presença. Somente alterando a data/hora de ao menos uma reunião para o momento atual é que o administrador consegue acessar a lista de presença daquela reunião. O Administrador deveria ser capaz de acessar e editar as listas e registrar presenças de qualquer reunião de qualquer consulta, em curso ou não.

https://www.loom.com/share/5c1b3a7adb05487483aa993d4e567483

**Comment by msantosmarcos** [comment]
demanda executada
