### ISSUE TITLE
Tela de exibição dos registros

### ISSUE THREAD

**Issue by msantosmarcos** [sep-es-br/participe-web#13]
-Ao cancelar uma determinada ação, o fluxo do sistema retorna normalmente para a tela de listagem sem atualizar a mesma. Queremos que ao retornar pra tela de listagem o sistema refaça a consulta.
- Ao clicar no subitem de menu o fluxo deverá ser o mesmo(retornar para tela de listagem atualizada)

**Comment by nataliafvilalva** [comment]
Foi criado o ticket PAR-57 no Jira para melhoria.

**Comment by nataliafvilalva** [comment]
Publicado para teste.
