### ISSUE TITLE
Formatação incorreta

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/participe-web#132]
Os cabeçalhos do menu Lista de Presença estão com a formatação do texto incompatível com o protótipo e com  os demais menus (Administração, Dashboard e Moderação)
Aplicação:
![image](https://user-images.githubusercontent.com/41954965/131730272-fd39ba6d-b574-40c1-88f5-ffbe83fe098f.png)
![image](https://user-images.githubusercontent.com/41954965/131730707-2fc8bc89-4032-46a6-be97-53253eb9335f.png)

Protótipo:
![image](https://user-images.githubusercontent.com/41954965/131730438-f355c55d-4767-4084-b653-39f17a7e28d5.png)
![image](https://user-images.githubusercontent.com/41954965/131730831-3767cf20-498d-4dd3-958e-834a268bac79.png)

**Comment by msantosmarcos** [comment]
demanda executada.
