### ISSUE TITLE
Erro ao registrar presença

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/participe-web#134]
Verificada mensagem de erro ao tentar registrar presença de usuário sem localidade na presente consulta.
A aplicação deveria abrir a página Registrar Presença e exigir o preenchimento da localidade para concluir o registro.
Ver gravação:
https://www.loom.com/share/79d56b14c7454511aa0ef9538698a9a4

**Comment by msantosmarcos** [comment]
demanda executada.
