### ISSUE TITLE
Impossível acrescentar Localidades ao Domínio

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/participe-web#15]
Uma vez criado um domínio, não é possível acrescentar localidades, já que o campo de seleção "Tipo" não apresenta as opções disponíveis (Estado, Microrregião, Município...).

![image](https://user-images.githubusercontent.com/41954965/73850177-f32dec00-4809-11ea-86aa-a6b864bff20f.png)

Como consequência, é impossível criar itens de plano cuja estrutura contenha localidade.

![image](https://user-images.githubusercontent.com/41954965/73850388-5a4ba080-480a-11ea-93b1-894ad9c2eadc.png)

**Comment by nataliafvilalva** [comment]
Foi criado o ticket PAR-54 para correção.

**Comment by nataliafvilalva** [comment]
Foi resolvido e testado, encontra-se funcionando.
Considerações: Toda vez que for limpar o banco deverá rodar o script que se encontra em"1.Registros iniciais" https://github.com/sep-es-br/participe-api
