### ISSUE TITLE
Campos preenchidos ficam sem rótulo

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/participe-web#16]
A maioria dos campos não tem rótulo fixo. O rótulo fica dentro do campo e desaparece assim que o campo é preenchido pela primeira vez. O problema é que quando se vai visualizar ou editar um objeto já criado, nenhum rótulo é exibido, apenas os valores dos campos, o que deixa dúvidas sobre o que significam aqueles valores.

Deveria ter um rótulo fixo (ou exibido após o preenchimento) superior ao campo, em fonte menor. Dentro do campo deveria ter uma breve orientação sobre como preenchê-lo. Cada campo demanda uma orientação diferente, por exemplo, pode ser uma máscara, algum limite, ou simplesmente uma indicação de seleção.

**Comment by nataliafvilalva** [comment]
Foi criado o ticket PAR-59 no Jira para correção.

**Comment by nataliafvilalva** [comment]
Publicado para teste.

**Comment by vdcordeiro** [comment]
Os rótulos foram fixados e as dicas aplicadas, no entanto não apresentam a informação correta.
![image](https://user-images.githubusercontent.com/41954965/74536182-4e509480-4f16-11ea-9070-672299803b6f.png)

![image](https://user-images.githubusercontent.com/41954965/74536236-69bb9f80-4f16-11ea-890a-a0a9fc255187.png)

![image](https://user-images.githubusercontent.com/41954965/74536275-86f06e00-4f16-11ea-963e-43bddbdfb5f7.png)

![image](https://user-images.githubusercontent.com/41954965/74536302-940d5d00-4f16-11ea-8328-17f57d2f68e2.png)

**Comment by alanrodrigo** [comment]
O rotulo "Nome do Plano" ainda aparece na criação de Planos

**Comment by alanrodrigo** [comment]
O rotulo "Nome da Estrutura" ainda aparece na criação de Estrutura

**Comment by alanrodrigo** [comment]
O Placeholder "Preencha com o nome do item do plano" ainda aparece na criação de Área Estratégica

**Comment by alanrodrigo** [comment]
O rotulo "Nome do Domínio" ainda aparece na criação do Domínio

**Comment by nataliafvilalva** [comment]
Publicado para teste com as alterações definidas em reunião com Vagner.
