### ISSUE TITLE
Erro ao inserir Domínio

### ISSUE THREAD

**Issue by msantosmarcos** [sep-es-br/participe-web#17]
Ao inserir município em mais de um microrregião esta apresentando o erro abaixo:

![image](https://user-images.githubusercontent.com/41967259/74149387-678bd500-4be6-11ea-9afc-36c15344fbb4.png)

**Comment by nataliafvilalva** [comment]
Foi ciado o ticket PAR-60 no Jira para correção.

**Comment by nataliafvilalva** [comment]
Publicado para teste.
