### ISSUE TITLE
Ao editar ou deletar um dominio

### ISSUE THREAD

**Issue by msantosmarcos** [sep-es-br/participe-web#20]
Quando o usuário efetua a pesquisa e deseja editar o excluir uma microrregião por exemplo e o mesmo salva ou cancela, o retorno para lista tem que apresentar a árvore aberta no nível que ele editou ou excluiu e não apresentar a árvore fechada. 

Obs.: Esse comportamento é padrão para todas as outras funcionalidades de pesquisa.

**Comment by nataliafvilalva** [comment]
Foi ciado o ticket PAR-65 no Jira para correção.
