### ISSUE TITLE
Datas Alterando Indevidamente 

### ISSUE THREAD

**Issue by laionF** [sep-es-br/participe-web#26]
Em administração na aba consulta, ao usar a opção de editar e logo depois salvar sem realizar nenhuma alteração as datas (Data Inicial e Data Final) mudam para o dia anterior:

Antes:
![image](https://user-images.githubusercontent.com/61193006/74740206-312f0500-5239-11ea-8eb2-a21f3cd2f89b.png)

Depois:
![image](https://user-images.githubusercontent.com/61193006/74740243-43a93e80-5239-11ea-96ba-ccaf8d4ac6e6.png)

**Comment by nataliafvilalva** [comment]
Corrigido e publicado para teste.

**Comment by laionF** [comment]
O problema ainda esta lá, mas agora são os meses que estão se comportando dessa maneira.

**Comment by nataliafvilalva** [comment]
Publicado para teste.
