### ISSUE TITLE
Navegação Incorreta - Aba Administração

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/participe-web#3]
Ao clicar na aba Administração, ela não fica selecionada.
Os 4 botões grandes que só deveriam aparecer quando a aba "Administração" é selecionada, já aparecem quando a aba Dashboard está selecionada.

**Comment by nataliafvilalva** [comment]
Foi criado o ticket PAR-46 no Jira para correção.

**Comment by nataliafvilalva** [comment]
Publicada para teste.
