### ISSUE TITLE
Inicialização da aplicação excessiva 

### ISSUE THREAD

**Issue by msantosmarcos** [sep-es-br/participe-web#32]
O tempo de inicialização da aplicação está excessiva demais.
Esta levando quase 18 segundos para entrar na aplicação, temos que reduzir bastante este tempo.

**Comment by nataliafvilalva** [comment]
Verificamos o problema, e ele somente ocorre ao entrar na aplicação pela primeira vez em um navegador, após isso não ocorrerá mais a lentidão.
