### ISSUE TITLE
Ícone incorreto

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/participe-web#4]
O ícone do botão [Novo] Domínio deveria ser o [+] comum, uma vez que não se está adicionando um novo domínio "dentro" de nada.
![Icone incorreto](https://user-images.githubusercontent.com/41954965/73377725-3f26e100-429e-11ea-88b1-9b4ceb64179e.PNG)

**Comment by nataliafvilalva** [comment]
Foi criado o ticket PAR-48 no Jira para correção.

**Comment by nataliafvilalva** [comment]
Publicada para teste.
