### ISSUE TITLE
Moderação

### ISSUE THREAD

**Issue by msantosmarcos** [sep-es-br/participe-web#43]
Na coluna de Área Estratégica esta sendo exibido o desafio, quando o correto é exibir a área.

![image](https://user-images.githubusercontent.com/41967259/86285333-cb756100-bbba-11ea-8bdf-a896986e0a19.png)

**Comment by msantosmarcos** [comment]
Resolvido

**Comment by vdcordeiro** [comment]
A correção foi feita alterando o título da coluna para Desafio. O título estava certo, os valores listados é que estavam errados. Na verdade, a coluna deve exibir a área estratégica, conforme definido no protótipo e não o desafio. 
![image](https://user-images.githubusercontent.com/41954965/86793400-cc3a4700-c041-11ea-80c6-455b18daf867.png)
