### ISSUE TITLE
Impossível associar moderadores a consulta

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/participe-web#48]
Na página de edição da consulta, seção Moderadores, a pesquisa não retorna os moderadores registrados no Acesso Cidadão, o que torna impossível a associação. Como consequência, os moderadores ficam impossibilitados de moderar os textos da consulta.
Para contornar o problema, tivemos que registrá-los também como administradores. Só assim eles conseguem visualizar os textos da consulta.

**Comment by vdcordeiro** [comment]
https://www.loom.com/share/4ba623e617e34cd8a437d2739d1c8e6a

**Comment by nataliafvilalva** [comment]
Testar novamente por favor.

**Comment by nataliafvilalva** [comment]
Criado ticket PAR-271 no JIRA para correção.
