### ISSUE TITLE
Erro ao salvar um domínio

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/participe-web#5]
Erro ao salvar um domínio com o nome _ESv1.0_
![image](https://user-images.githubusercontent.com/41954965/73378345-397dcb00-429f-11ea-8225-1ace0756c77b.png)

**Comment by nataliafvilalva** [comment]
De acordo com os teste realizados após a criação desse bug, não foi encontrado o problema descrito. Por favor descrever o passo a passo de como reproduzir o bug ou testar novamente.
https://www.loom.com/share/e396ee6da9014c829811c3e4d1db28c8

**Comment by nataliafvilalva** [comment]
Bug resolvido de acordo com @msantosmarcos
