### ISSUE TITLE
Favicon incorreto

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/participe-web#6]
Deve utilizar o ícone do participe.

![image](https://user-images.githubusercontent.com/41954965/73379160-8f06a780-42a0-11ea-824d-36a67e7f3dc6.png)

**Comment by nataliafvilalva** [comment]
Foi criado o ticket PAR-49 no Jira para correção.

**Comment by nataliafvilalva** [comment]
Publicada para teste.

**Comment by vdcordeiro** [comment]
O Favicon está com fundo branco. Deveria ser transparente (padrão de utilização).

**Comment by alanrodrigo** [comment]
Favicon está sendo exibido corretamente!
