### ISSUE TITLE
Coluna Área Estratégica na lista de propostas

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/participe-web#63]
A lista de propostas da moderação não está exibindo a coluna Área Estratégica para todas, somente para as que estão associadas à área estratégica. Deveria exibir a área estratégica sempre, inclusive para as propostas/comentários associados a desafios.
![image](https://user-images.githubusercontent.com/41954965/87305820-7821dd80-c4ed-11ea-9b2d-845ed0763b73.png)

**Comment by nataliafvilalva** [comment]
De acordo com o protótipo, o sistema apresenta nessa coluna o lugar onde a proposta foi vinculada, se foi vinculada a uma área estratégica, apresenta a área estratégica na coluna, se foi vinculada a um desafio, ele apresenta o desafio na coluna e assim por diante.
![image](https://user-images.githubusercontent.com/60435042/94691434-49065580-02ff-11eb-9ee4-a1405db68164.png)
