### ISSUE TITLE
Texto com idade errada na página de moderação 

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/participe-web#65]
Na página de moderação, a idade do texto está errada. Aparece sempre 2 horas, para todos os textos.
![image](https://user-images.githubusercontent.com/41954965/87347731-12077b80-c52a-11ea-8837-b1f871110161.png)
![image](https://user-images.githubusercontent.com/41954965/87347758-1c297a00-c52a-11ea-9300-f966f114e8f8.png)

**Comment by nataliafvilalva** [comment]
Criado ticket PAR-268 no JIRA para correção.
