### ISSUE TITLE
Ao exibir a lista de domínios vazia esta sendo apresentada um informação de erro cujo arquivo em anexo

### ISSUE THREAD

**Issue by msantosmarcos** [sep-es-br/participe-web#7]
![dominio](https://user-images.githubusercontent.com/41967259/73453323-88346f00-434a-11ea-94a8-e7f0f2e4525d.jpg)

**Comment by nataliafvilalva** [comment]
Foi criado o ticket PAR-51 no Jira para correção.

**Comment by nataliafvilalva** [comment]
Testado e resolvido de acordo com @msantosmarcos
