### ISSUE TITLE
Comportamento incorreto na Administração de Cidadãos

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/participe-web#77]
Na guia **Administração > Cidadão**, a função de seleção de consultas está apresentando comportamento incorreto.
- A caixa de diálogo de seleção de consultas exibe o título "Selecione a consulta que deseja moderar". Não é moderação.
- Somente as consultas vigentes estão sendo exibidas;

![image](https://user-images.githubusercontent.com/41954965/94183268-8b034780-fe78-11ea-88d6-ad17b69ac177.png)

**Comment by nataliafvilalva** [comment]
Criado ticket PAR-269 no JIRA para correção.

**Comment by MateusFirmino** [comment]
Ja foi resolvido , correção feita em 28 de outubro de 2020.
