### ISSUE TITLE
Agora os dados estão sendo inseridos, no entanto preciso efetuar um refresh na tela da aplicação para que o registro novo seja exibido e ainda assim sobe o modal de erro.

### ISSUE THREAD

**Issue by msantosmarcos** [sep-es-br/participe-web#8]
Agora os dados estão sendo inseridos, no entanto preciso efetuar um refresh na tela da aplicação para que o registro novo seja exibido e ainda assim sobe o modal de erro.
segue tela abaixo:

![lista de domains](https://user-images.githubusercontent.com/41967259/73557912-e50a5500-4430-11ea-8386-e0b624c1e001.png)

**Comment by nataliafvilalva** [comment]
Foi criado o ticket PAR-52 no Jira para correção.

**Comment by nataliafvilalva** [comment]
Publicado para teste.
