### ISSUE TITLE
Ajustar Fuso horário

### ISSUE THREAD

**Issue by alanrodrigo** [sep-es-br/participe-web#80]
![image](https://user-images.githubusercontent.com/42146539/94602208-f11e0f00-026a-11eb-97ee-f2b52262d6bc.png)

Fuso horário adiantado em 3 horas

**Comment by nataliafvilalva** [comment]
De acordo com nossos testes, o horário está com esse fuso porque o servidor da SEP está assim, quando testamos local o sistema pega o horário da nossa máquina normalmente. Por favor verificar isso no servidor.
