### ISSUE TITLE
Impossível atribuir moderadores a uma consulta

### ISSUE THREAD

**Issue by felipecsalles** [sep-es-br/participe-web#82]
![image](https://user-images.githubusercontent.com/71851259/94613728-70b3da00-027b-11eb-8f6c-060c7c6d72b6.png)

**Comment by vdcordeiro** [comment]
A busca por moderadores não retorna nenhum usuário moderador, ainda que estejam configurados como tal no Acesso Cidadão.

**Comment by vdcordeiro** [comment]
Atribuida a tag (critical), pois esse bug impede a realização de outros testes, com credenciais de moderadores.

**Comment by nataliafvilalva** [comment]
Criado ticket PAR-272 no JIRA para correção.

**Comment by vdcordeiro** [comment]
Resolvido. Tratava-se de um problema na configuração do arquivo de propriedades no Jenkins.
