### ISSUE TITLE
Rótulos incorretos na página de criação de reunião presencial

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/participe-web#84]
Rótulos diferentes da documentação aprovada.
1. Falta o título da página (ação);
2. Datas com rótulo incorreto;
3. O rótulo de localidade (Município no exemplo) deve ficar fora do controle, com fundo branco;
4. O rótulo de Abrangência deve ficar fora do controle, com fundo branco;
5. A busca do recepcionista é por E-mail. Não é por nome.

Implementação:
![image](https://user-images.githubusercontent.com/41954965/94719348-71a34500-0329-11eb-9761-60a5899c0bfd.png)

Documentação:
![image](https://user-images.githubusercontent.com/41954965/94718816-a662cc80-0328-11eb-89d3-7db17d784562.png)

**Comment by nataliafvilalva** [comment]
Criado ticket PAR-273 no JIRA para correção.
