### ISSUE TITLE
Impossível atribuir recepcionistas a uma reunião presencial

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/participe-web#85]
A busca por recepcionistas não retorna nenhum usuário recepcionista, ainda que estejam configurados como tal no Acesso Cidadão.

![image](https://user-images.githubusercontent.com/41954965/94721320-1aeb3a80-032c-11eb-962c-8a7cf919fd8b.png)

**Comment by nataliafvilalva** [comment]
Criado ticket PAR-272 no JIRA para correção.

**Comment by vdcordeiro** [comment]
Resolvido. Era um erro no arquivo de configuração de homologação no Jenkins
