### ISSUE TITLE
Lista de Presença - Fuso horário

### ISSUE THREAD

**Issue by alanrodrigo** [sep-es-br/participe-web#86]
Ajustar fuso horário
![image](https://user-images.githubusercontent.com/42146539/94724609-eded5680-0330-11eb-87db-dc5d79f63c6f.png)

**Comment by nataliafvilalva** [comment]
De acordo com nossos testes, o horário está com esse fuso porque o servidor da SEP está assim, quando testamos local o sistema pega o horário da nossa máquina normalmente. Por favor verificar isso no servidor.
