### ISSUE TITLE
Editar lista de presença

### ISSUE THREAD

**Issue by alanrodrigo** [sep-es-br/participe-web#87]
Ao abrir a tela de edição da lista de presença não é carregado na tela os participantes já adicionados

![image](https://user-images.githubusercontent.com/42146539/94732102-2f373380-033c-11eb-962f-b2dd158f9dca.png)

**Comment by nataliafvilalva** [comment]
Para carregar os participantes, você deve inserir algum filtro.
![Uploading image.png…]()

**Comment by alanrodrigo** [comment]
Comportamento proposital
