### ISSUE TITLE
Os administradores não conseguem moderar as consultas encerradas

### ISSUE THREAD

**Issue by msantosmarcos** [sep-es-br/participe-web#88]
Os administradores não conseguem moderar as consultas encerradas. O erro exibido na imagem abaixo não esta condizente com a origem do problema, favor exibir uma mensagem de erro adequada para esta situação.

Então, são duas situações:

1- O Administrador terá permissão de visualizar todas as propostas da consulta a que ele estará vinculado; 
2 - Moderador não terá permissão.

![image](https://user-images.githubusercontent.com/41967259/94842623-feb1d100-03f1-11eb-8001-1d554369f0c8.png)

**Comment by nataliafvilalva** [comment]
Criado ticket PAR-277 no JIRA para correção.

**Comment by vdcordeiro** [comment]
Corrigindo:
Então, são duas situações:

1- O Administrador terá permissão de moderar todas as propostas de todas as consultas, em qualquer momento, consultas abertas ou encerradas;
2 - O Moderador só tem permissão para moderar as consultas às quais está vinculado e que estão abertas no momento.
