### ISSUE TITLE
Error fetching types

### ISSUE THREAD

**Issue by vdcordeiro** [sep-es-br/participe-web#9]
Ao selecionar no menu "Administração" a opção "Estrutura", "Plano" ou "Consulta" e depois selecionar "Domain", a mensagem "Error fetching types é exibida".
![image](https://user-images.githubusercontent.com/41954965/73571458-52c47a00-444d-11ea-8cf5-9e9454321b6b.png)

**Comment by nataliafvilalva** [comment]
Foi criado o ticket PAR-55 para correção.

**Comment by nataliafvilalva** [comment]
Publicado para teste.
